#pragma once

#define GE_MOUSE_BUTTON_LEFT 0
#define GE_MOUSE_BUTTON_RIGHT 1
#define GE_MOUSE_BUTTON_MIDDLE 2
#define GE_MOUSE_BUTTON_4 3
#define GE_MOUSE_BUTTON_5 4
#define GE_MOUSE_BUTTON_6 5
#define GE_MOUSE_BUTTON_7 6
#define GE_MOUSE_BUTTON_8 7
